import {StyleSheet} from 'react-native';
import {getFigmaDimension, getScreenHeight} from '../../../helpers/screenSize';
import {ColorPalette} from '../../../config/colorPalette';

export const styles = StyleSheet.create({
  mainContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: getFigmaDimension(16),
    paddingVertical: getFigmaDimension(16),
  },
  scrollContent: {
    gap: getFigmaDimension(16),
  },
  verifyContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(20),
    gap: getFigmaDimension(20),
    backgroundColor: ColorPalette.White,
    borderRadius: getFigmaDimension(12),
  },
  textVerifyContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: getFigmaDimension(4),
  },
  textOne: {
    fontSize: 16,
    color: ColorPalette.GREY_TEXT_500,
  },
  textTwo: {
    color: ColorPalette.GREY_TEXT_300,
    fontSize: 11,
  },
  verifyStepsContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: getFigmaDimension(8),
    paddingVertical: getFigmaDimension(12),
    backgroundColor: ColorPalette.PRIMARY_WHITE_SELLER,
    borderRadius: getFigmaDimension(12),
    height: 300,
  },
  OrderContainer: {
    borderRadius: getFigmaDimension(12),
    backgroundColor: ColorPalette.White,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    paddingVertical: getFigmaDimension(8),
  },
  menuContainer: {
    padding: getFigmaDimension(12),
  },
  leftIconBackgroundColor: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: getFigmaDimension(8),
    borderRadius: getFigmaDimension(8),
  },
  statsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: getFigmaDimension(16),
  },
  containerOne: {
    display: 'flex',
    flexDirection: 'row',
    gap: getFigmaDimension(16),
  },
  containerTwo: {
    display: 'flex',
    flexDirection: 'row',
    gap: getFigmaDimension(16),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalSales: {
    flex: 2,
    backgroundColor: ColorPalette.White,
    paddingVertical: getFigmaDimension(20),
    paddingHorizontal: getFigmaDimension(16),
    borderRadius: getFigmaDimension(8),
    flexDirection: 'column',
    gap: getFigmaDimension(17),
  },
  salesOne: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    gap: getFigmaDimension(39),
  },
  salesTwo: {
    display: 'flex',
    flexDirection: 'column',
  },
  iconBack: {
    display: 'flex',
    borderRadius: getFigmaDimension(8),
    padding: getFigmaDimension(8),
    backgroundColor: 'rgba(31, 193, 107, 0.10)',
  },
  iconBackSale: {
    display: 'flex',
    borderRadius: getFigmaDimension(8),
    padding: getFigmaDimension(8),
    backgroundColor: 'rgba(31, 193, 107, 0.10)',
  },
  iconBackOne: {
    display: 'flex',
    borderRadius: getFigmaDimension(8),
    padding: getFigmaDimension(8),
    backgroundColor: 'rgba(145, 1, 207, 0.10)',
  },
  iconBackTwo: {
    display: 'flex',
    borderRadius: getFigmaDimension(4),
    padding: getFigmaDimension(4),
    backgroundColor: 'rgba(208, 4, 22, 0.10)',
  },
  iconBackThree: {
    display: 'flex',
    borderRadius: getFigmaDimension(4),
    padding: getFigmaDimension(4),
    backgroundColor: 'rgba(223, 180, 0, 0.10)',
  },
  countBlock: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: getFigmaDimension(4),
  },
  countText: {
    color: ColorPalette.RiseText,
    fontSize: 14,
  },
  countValue: {
    color: ColorPalette.GREY_TEXT_500,
  },
  countCaptionContainer: {
    flexDirection: 'row',
  },
  countCaption: {
    color: ColorPalette.GREY_TEXT_300,
  },
  countCaptionOne: {
    color: ColorPalette.PURPLE_300,
  },
  activeProduct: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    padding: getFigmaDimension(16),
    backgroundColor: ColorPalette.White,
    borderRadius: getFigmaDimension(8),
    gap: getFigmaDimension(20),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stockContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: getFigmaDimension(8),
    padding: getFigmaDimension(16),
    backgroundColor: ColorPalette.White,
    borderRadius: getFigmaDimension(8),
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  salesOverview: {
    display: 'flex',
    borderRadius: getFigmaDimension(12),
    backgroundColor: ColorPalette.White,
    paddingVertical: getFigmaDimension(16),
    paddingHorizontal: getFigmaDimension(12),
    flexDirection: 'column',
    gap: getFigmaDimension(24),
  },
  salesHeading: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  LeftHeading: {
    display: 'flex',
    flexDirection: 'column',
  },
  rightHeadingButtons: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: getFigmaDimension(4),
    flexDirection: 'row',
    gap: getFigmaDimension(4),
    backgroundColor: ColorPalette.ButtonBackHome,
    borderRadius: getFigmaDimension(8),
  },
  salesGraph: {
    display: 'flex',
    width: getFigmaDimension(334),
    height: getFigmaDimension(250),
  },
  recentOrdersContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingVertical: getFigmaDimension(20),
    paddingHorizontal: getFigmaDimension(12),
    gap: getFigmaDimension(20),
    backgroundColor: ColorPalette.White,
    borderRadius: getFigmaDimension(12),
  },
  recentOrderTitle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewAll: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewAllText: {
    color: ColorPalette.PURPLE_200,
  },
  recentAllOrders: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  twoContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: getFigmaDimension(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerAnother: {
    display: 'flex',
    flexDirection: 'row',
    gap: getFigmaDimension(18),
  },
  containerAnotherOne: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: getFigmaDimension(16),
  },
  containerProportional: {
    display: 'flex',
    flexDirection: 'column',
    gap: getFigmaDimension(16),
  },
});
