import {StyleSheet} from 'react-native';
import {getFigmaDimension, getScreenHeight} from '../../../helpers/screenSize';
import {ColorPalette} from '../../../config/colorPalette';

export const styles = StyleSheet.create({
  mainContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: getFigmaDimension(16),
    paddingVertical: getFigmaDimension(16),
  },
  scrollContent: {
    gap: getFigmaDimension(16),
  },
  verifyContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: getFigmaDimension(12),
    paddingVertical: getFigmaDimension(20),
    gap: getFigmaDimension(20),
    backgroundColor: ColorPalette.BackgroundPrimary,
    borderRadius: getFigmaDimension(12),
  },
  textVerifyContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: getFigmaDimension(4),
  },
  textTwo: {
    color: ColorPalette.TextSecondary,
  },
  verifyStepsContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingHorizontal: getFigmaDimension(8),
    paddingVertical: getFigmaDimension(12),
    backgroundColor: ColorPalette.ContainerBack,
    borderRadius: getFigmaDimension(12),
    height: 300,
  },
  OrderContainer: {
    height: 250,
    borderRadius: getFigmaDimension(12),
    backgroundColor: ColorPalette.BackgroundPrimary,
  },
  statsContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: getFigmaDimension(16),
  },
  containerOne: {
    display: 'flex',
    flexDirection: 'row',
    gap: getFigmaDimension(16),
  },
  containerTwo: {
    display: 'flex',
    flexDirection: 'row',
    gap: getFigmaDimension(16),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  totalSales: {
    flex: 2,
    backgroundColor: ColorPalette.BackgroundPrimary,
    paddingVertical: getFigmaDimension(20),
    paddingHorizontal: getFigmaDimension(16),
    borderRadius: getFigmaDimension(8),
    flexDirection: 'column',
    gap: getFigmaDimension(17),
  },
  salesOne: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    gap: getFigmaDimension(39),
  },
  salesTwo: {
    display: 'flex',
    flexDirection: 'column',
  },
  iconBack: {
    display: 'flex',
    borderRadius: getFigmaDimension(8),
    padding: getFigmaDimension(8),
    backgroundColor: ColorPalette.IconBack,
  },
  iconBackOne: {
    display: 'flex',
    borderRadius: getFigmaDimension(8),
    padding: getFigmaDimension(8),
    backgroundColor: ColorPalette.HomeBack,
  },
  iconBackTwo: {
    display: 'flex',
    borderRadius: getFigmaDimension(4),
    padding: getFigmaDimension(4),
    backgroundColor: ColorPalette.IconMini,
  },
  iconBackThree: {
    display: 'flex',
    borderRadius: getFigmaDimension(4),
    padding: getFigmaDimension(4),
    backgroundColor: ColorPalette.smallBack,
  },
  countBlock: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: getFigmaDimension(4),
  },
  countText: {
    color: ColorPalette.countColor,
  },
  countValue: {
    color: ColorPalette.TextPrimary,
  },
  countCaption: {
    color: ColorPalette.TextSecondary,
  },
  activeProduct: {
    flex: 1,
    display: 'flex',
    flexDirection: 'row',
    padding: getFigmaDimension(16),
    backgroundColor: ColorPalette.BackgroundPrimary,
    borderRadius: getFigmaDimension(8),
    gap: getFigmaDimension(20),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stockContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: getFigmaDimension(8),
    padding: getFigmaDimension(16),
    backgroundColor: ColorPalette.BackgroundPrimary,
    borderRadius: getFigmaDimension(8),
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  salesOverview: {
    display: 'flex',
    borderRadius: getFigmaDimension(12),
    backgroundColor: ColorPalette.BackgroundPrimary,
    paddingVertical: getFigmaDimension(16),
    paddingHorizontal: getFigmaDimension(12),
    flexDirection: 'column',
    gap: getFigmaDimension(24),
  },
  salesHeading: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  LeftHeading: {
    display: 'flex',
    flexDirection: 'column',
  },
  rightHeadingButtons: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: getFigmaDimension(4),
    flexDirection: 'row',
    gap: getFigmaDimension(4),
    backgroundColor: ColorPalette.ButtonBackHome,
    borderRadius: getFigmaDimension(8),
  },
  salesGraph: {
    display: 'flex',
    width: getFigmaDimension(334),
    height: getFigmaDimension(250),
  },
  recentOrdersContainer: {
    display: 'flex',
    flexDirection: 'column',
    paddingVertical: getFigmaDimension(20),
    paddingHorizontal: getFigmaDimension(12),
    gap: getFigmaDimension(20),
    backgroundColor: ColorPalette.BackgroundPrimary,
    borderRadius: getFigmaDimension(12),
  },
  recentOrderTitle: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  viewAll: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewAllText: {
    color: ColorPalette.ViewAll,
  },
  recentAllOrders: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  twoContainer: {
    display: 'flex',
    flexDirection: 'row',
    gap: getFigmaDimension(20),
    alignItems: 'center',
    justifyContent: 'center',
  },
});
